### PR TITLE
TLS support

### PR DESCRIPTION
**Pull request by ldettwy**
Cryptol: https://github.com/GaloisInc/cryptol/pull/1203

### CODE REVIEW

**Comment by pnwamk** [comment]
Wish list/thoughts, for this PR or a subsequent one (I'm very willing to implement these as well after wrapping up a `cryptol-remote-api` feature I've got cooking at the moment):
+ TLS tests for our echo server
+ Any python client features necessary to make TLS-related interactions smoother (e.g., right now you can't disable certificate verification, which seems highly useful when testing things)
+ Possibly a way to customize where the server looks for the certificate/key to conveniently support more deployment scenarios

**Comment by atomb** [comment]
I added an issue, #168, for the second bullet.

**Comment by pnwamk** [comment]
This now addresses https://github.com/GaloisInc/argo/issues/168 and has a TLS test in CI.

One notable change: this adds `scotty-tls` as a submodule, since we depend on the changes in `scotty-tls v0.4.6` which have been merged but not yet published to hackage. See https://github.com/scotty-web/scotty-tls/pull/9

**Comment by pnwamk** [comment]
Additional to do: bump argo_client version and publish to PyPi.

**Review by atomb — APPROVED** [review]
This looks great. Thanks!

**Pull request merged**
